name: Build and deploy Astro SSR app to Azure Web App - mihuellaapp

on:
  push:
    branches:
      - azure
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies and build Astro SSR
        working-directory: Frontend
        run: |
          npm install
          npm run build

      - name: Prepare artifact for deployment
        run: |
          # Copiamos la carpeta dist y server, package.json, node_modules etc que se necesitan para SSR
          mkdir -p deploy-package
          cp -r Frontend/dist deploy-package/
          cp -r Frontend/server deploy-package/
          cp Frontend/package.json deploy-package/
          cp -r Frontend/node_modules deploy-package/

      - name: Zip deployment package
        run: |
          cd deploy-package
          zip -r ../deploy.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: astro-ssr-deploy
          path: deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment: production
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: astro-ssr-deploy

      - name: Unzip deployment package
        run: unzip deploy.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C296E570C9E541E9A4D40C8BBABE1536 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B48EBDB3AD424A08AC07861374066323 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_45F5D2AE79924F6CBA876E80DD8670A8 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mihuellaapp'
          slot-name: 'Production'
          package: .
